import type { CardData } from "./card-utils";

/** Curated demo data used in the hero card + /demo preview. */
export const DEMO_CARD: CardData = {
  cardId: "demo",
  stats: {
    claude: {
      sessions: 847,
      cost: 412.83,
      inputTokens: 18_420_000,
      outputTokens: 3_610_000,
      cacheReadTokens: 92_100_000,
      cacheCreateTokens: 14_800_000,
      cacheSavingsUsd: 312.4,
      models: {
        "claude-opus-4-6": { sessions: 312, cost: 238.9 },
        "claude-sonnet-4-6": { sessions: 498, cost: 168.2 },
        "claude-haiku-4-5": { sessions: 37, cost: 5.73 },
      },
      topTools: [
        { name: "Edit", count: 4820 },
        { name: "Read", count: 3910 },
        { name: "Bash", count: 2640 },
        { name: "Grep", count: 1380 },
        { name: "Write", count: 960 },
        { name: "Glob", count: 740 },
        { name: "Skill", count: 220 },
        { name: "WebSearch", count: 95 },
      ],
      totalToolCalls: 14_765,
      hourDistribution: [
        2, 1, 0, 0, 0, 0, 1, 3, 6, 14, 28, 41,
        58, 72, 81, 92, 76, 64, 52, 38, 29, 21, 14, 7,
      ],
      activeDays: 42,
      projects: [
        { name: "bematist", sessions: 382, cost: 198.4 },
        { name: "analytics-service", sessions: 206, cost: 104.5 },
        { name: "collector", sessions: 128, cost: 68.1 },
        { name: "dashboard", sessions: 89, cost: 32.2 },
        { name: "infra", sessions: 42, cost: 9.6 },
      ],
    },
    codex: {
      sessions: 184,
      cost: 48.7,
      inputTokens: 4_120_000,
      cachedInputTokens: 1_840_000,
      outputTokens: 920_000,
      models: {
        "gpt-5.3-codex": { sessions: 128, cost: 38.4 },
        "gpt-5.2-codex": { sessions: 56, cost: 10.3 },
      },
      activeDays: 19,
      projects: [
        { name: "bematist", sessions: 92, cost: 27.8 },
        { name: "collector", sessions: 54, cost: 14.1 },
        { name: "infra", sessions: 38, cost: 6.8 },
      ],
      topTools: [
        { name: "apply_patch", count: 612 },
        { name: "exec_command", count: 348 },
        { name: "read_file", count: 210 },
      ],
      totalToolCalls: 1_170,
      totalReasoningBlocks: 4_218,
      totalWebSearches: 31,
    },
    combined: {
      totalCost: 461.53,
      totalSessions: 1_031,
      totalInputTokens: 22_540_000,
      totalOutputTokens: 4_530_000,
      totalActiveDays: 47,
      dailyDistribution: [],
    },
    highlights: {
      favoriteModel: "claude-sonnet-4-6",
      favoriteTool: "Edit",
      peakHour: 15,
      peakHourLabel: "3 PM",
      personality: "The Daylight Builder",
      totalToolCalls: 15_935,
      cacheHitRate: 0.82,
      longestStreak: 18,
      mostExpensiveSession: {
        cost: 14.8,
        model: "claude-opus-4-6",
        project: "bematist",
        date: "2026-04-02",
      },
      avgCostPerSession: 0.45,
      avgSessionsPerDay: 21.9,
      mcpServers: [],
      totalMcpCalls: 0,
      skillInvocations: 220,
      builtinTools: [],
      readWriteRatio: { reads: 3910, writes: 960, ratio: "4.07" },
      costWithoutCache: 774.2,
      activityCategories: [
        {
          category: "Building",
          description: "New features, modules, and surfaces",
          sessions: 412,
          sessionPct: 40,
          cost: 198.6,
          costPct: 43,
        },
        {
          category: "Investigating",
          description: "Reading and tracing existing code",
          sessions: 258,
          sessionPct: 25,
          cost: 98.4,
          costPct: 21,
        },
        {
          category: "Debugging",
          description: "Fixing bugs, reproducing issues",
          sessions: 186,
          sessionPct: 18,
          cost: 84.2,
          costPct: 18,
        },
        {
          category: "Testing",
          description: "Writing and running tests",
          sessions: 92,
          sessionPct: 9,
          cost: 41.8,
          costPct: 9,
        },
        {
          category: "Refactoring",
          description: "Restructuring without changing behavior",
          sessions: 58,
          sessionPct: 6,
          cost: 28.3,
          costPct: 6,
        },
        {
          category: "Other",
          description: "Everything else",
          sessions: 25,
          sessionPct: 2,
          cost: 10.2,
          costPct: 3,
        },
      ],
    },
  },
  user: {
    displayName: "Demo Developer",
    photoURL: "",
    githubUsername: "demo-dev",
  },
  createdAt: "2026-04-17T00:00:00.000Z",
};
